mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'polls'
urlpatterns = [
        path('', TemplateView.as_view(template_name='polls/main.html')),
        path("some", views.some, name="some"),
        path("remain/<slug:guess>", views.RestMainView.as_view()),
        path("remain2", views.RestMainView2.as_view(), name="remain2"),
        ]

polls/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

mysite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

polls/views.py
from django.http import HttpResponse
from django.utils.html import escape
from django.views import View
from django.shortcuts import render

msg = '{ "game1": [ ["e2", "e4"], ["e7", "e5"] ] }'
def some(request):
    return HttpResponse(msg, content_type='application/json')

class RestMainView(View) :
    def get(self, request, guess):
        f = ['1', '2', '3']
        ctx = {'guess' : int(guess),
               'numbers' : f,
               'zap' : '<b>bold</b>'
                }
        return render(request, 'polls/cond.html', ctx)

class RestMainView2(View) :
    def get(self, request):
        ctx = { 'zap' : '<b>bold</b>' }
        return render(request, 'polls/cond2.html', ctx)

polls/templates/polls/base.html
<html>
    <head>
        <title>Base template</title>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

polls/templates/polls/cond.html
{% extends "polls/base.html" %}

{% block content %}
<p>Your guess was {{ guess }}</p>
<p> {{ zap|safe }} </p>
<ul>
    {% for x in numbers %}
    <li>{{ x }}</li>
    {% endfor %}
</ul>
<p><a href="{% url 'polls:remain2' %}">link</a></p>
{% endblock %}

polls/templates/polls/cond2.html
{% extends "polls/base.html" %}

{% block content %}
<p> {{ zap|safe }} </p>
{% endblock %}

polls/templates/polls/main.html
{% extends "base.html" %}

{% block content %}

<h1>Hi!</h1>

{% endblock content %}

templates/base.html
{% load django_vite %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">

    {% vite_hmr_client %}
    {% vite_asset 'js/main.js' %}
        
        <!--<link rel="stylesheet" href="/static/style.css">-->
        <title>pythonanywhere django test</title>
    </head>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

templates/home.html
{% extends "base.html" %} {% block content %}

<h1>Home</h1>
<p>/polls</p>

<div x-data="{ open: false }">
    <button @click="open = !open">Toggle show</button>

    <span x-show="open"> Content... </span>
</div>

{% endblock content %}